name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - app/**

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GH_EC2T_PF }}" | docker login ghcr.io -u ${{ secrets.GH_PF }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ secrets.GH_PF }}/fastapi-app:latest ./app

      - name: Push Docker image
        run: docker push ghcr.io/${{ secrets.GH_PF }}/fastapi-app:latest